apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: parentinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parentinfo
  template:
    metadata:
      labels:
        app: parentinfo
    spec:
      containers:
        - name: django
          image: ruchany13/parentinfo:0.1
          envFrom:
            - secretRef:
                name: parentinfo-secret
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: parentinfo-r2-secret
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: static-volume
              mountPath: /app/static
            - name: media-volume
              mountPath: /app/media
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-pvc-parentinfo
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc-parentinfo
