apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: parentinfo
spec:
  selector:
    app: postgres-parentinfo
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
