apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: parentinfo
type: Opaque
data:
  POSTGRES_DB: bXlkYg==  #   "mydb"
  POSTGRES_USER: bXl1c2Vy  #   "myuser"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  #   "password"
